-- =====================================================================
-- KLPS - Knowledge Learning Preservation System
-- CLEAN SCHEMA (structure + reference data, no user data)
--
-- Generated from the live `klps` database with:
--   mysqldump --no-data --routines --triggers --events
--
-- CONTENTS
--   13 tables, 1 view, 1 stored function, 2 triggers
--   + reference data: departments (5), knowledge_categories (9)
--
-- DELIBERATELY EXCLUDED
--   No rows from users, knowledge, knowledge_votes, knowledge_comments,
--   knowledge_saves, knowledge_views, notifications, activity_logs,
--   ai_conversations, ai_messages, email_otp. Nothing personal, and no
--   password hashes, ships with the schema.
--
--   email_otp is included as an EMPTY table on purpose: register.php,
--   send_otp.php and verify_otp.php all read and write it, so dropping it
--   breaks account creation entirely.
--
-- ID CONVENTION
--   Every primary key is a readable prefixed code (D001, U001, K001 ...),
--   never AUTO_INCREMENT. IDs are generated by new_id() in
--   config/config.php, NOT by the database. Do not reintroduce
--   AUTO_INCREMENT on these columns.
--
-- TIMEZONE
--   TIMESTAMP columns hold Asia/Singapore local time. config/config.php
--   pins both PHP and the MySQL session to +08:00; keep them matched.
--
-- BEFORE USING IN PRODUCTION
--   1. This file must NOT be web-reachable. Deny /database/ via .htaccess.
--   2. Create a least-privilege MySQL user; do not run the app as root.
--   3. Three columns are indexed but carry no FOREIGN KEY:
--      users.department_id, knowledge.department_id, knowledge.category_id.
--      Verified 0 orphans today, so constraints can be added safely.
-- =====================================================================

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `activity_logs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `activity_logs` (
  `activity_logs_id` varchar(16) NOT NULL,
  `user_id` varchar(16) DEFAULT NULL,
  `action` varchar(100) NOT NULL DEFAULT '',
  `details` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`activity_logs_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `fk_activity_logs_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`users_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ai_conversations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ai_conversations` (
  `ai_conversations_id` varchar(16) NOT NULL,
  `user_id` varchar(16) DEFAULT NULL,
  `title` varchar(200) NOT NULL DEFAULT '',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `contributed_knowledge_id` varchar(16) DEFAULT NULL,
  PRIMARY KEY (`ai_conversations_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `fk_ai_conversations_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`users_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ai_messages`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ai_messages` (
  `ai_messages_id` varchar(16) NOT NULL,
  `conversation_id` varchar(16) DEFAULT NULL,
  `sender` enum('user','ai','system') NOT NULL,
  `message` longtext NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ai_messages_id`),
  KEY `idx_conversation_time` (`conversation_id`,`created_at`),
  CONSTRAINT `fk_ai_messages_conversation_id` FOREIGN KEY (`conversation_id`) REFERENCES `ai_conversations` (`ai_conversations_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `contribution_summary`;
/*!50001 DROP VIEW IF EXISTS `contribution_summary`*/;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
/*!50001 CREATE VIEW `contribution_summary` AS SELECT
 1 AS `users_id`,
  1 AS `employee_name`,
  1 AS `total_articles`,
  1 AS `total_votes_received`,
  1 AS `helpful_ratio` */;
SET character_set_client = @saved_cs_client;
DROP TABLE IF EXISTS `departments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `departments` (
  `departments_id` varchar(16) NOT NULL,
  `name` varchar(100) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`departments_id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `email_otp`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `email_otp` (
  `id` varchar(16) NOT NULL,
  `email` varchar(150) NOT NULL,
  `otp_code` varchar(255) NOT NULL,
  `attempts` int(10) unsigned DEFAULT 0,
  `is_verified` tinyint(1) DEFAULT 0,
  `expires_at` datetime NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `knowledge`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `knowledge` (
  `knowledge_id` varchar(16) NOT NULL,
  `category_id` varchar(16) DEFAULT NULL,
  `department_id` varchar(16) DEFAULT NULL,
  `created_by` varchar(16) DEFAULT NULL,
  `title` varchar(200) NOT NULL,
  `problem` text NOT NULL,
  `cause` text NOT NULL,
  `solution` text NOT NULL,
  `procedure_steps` text NOT NULL,
  `best_practice` text NOT NULL,
  `status` enum('draft','active','archived') NOT NULL DEFAULT 'active',
  `view_count` int(10) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `tags` varchar(255) NOT NULL DEFAULT '',
  `helpful_count` int(11) NOT NULL DEFAULT 0,
  `not_helpful_count` int(11) NOT NULL DEFAULT 0,
  `save_count` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`knowledge_id`),
  KEY `category_id` (`category_id`),
  KEY `department_id` (`department_id`),
  KEY `created_by` (`created_by`),
  FULLTEXT KEY `ft_knowledge` (`title`,`problem`,`cause`,`solution`,`procedure_steps`,`best_practice`),
  CONSTRAINT `fk_knowledge_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`users_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `knowledge_categories`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `knowledge_categories` (
  `knowledge_categories_id` varchar(16) NOT NULL,
  `name` varchar(100) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`knowledge_categories_id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `knowledge_comments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `knowledge_comments` (
  `knowledge_comments_id` varchar(16) NOT NULL,
  `user_id` varchar(16) DEFAULT NULL,
  `knowledge_id` varchar(16) DEFAULT NULL,
  `parent_id` varchar(16) DEFAULT NULL,
  `comment` text NOT NULL,
  `is_edited` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `is_read` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`knowledge_comments_id`),
  KEY `user_id` (`user_id`),
  KEY `parent_id` (`parent_id`),
  KEY `idx_knowledge_comments` (`knowledge_id`,`created_at`),
  CONSTRAINT `fk_knowledge_comments_knowledge_id` FOREIGN KEY (`knowledge_id`) REFERENCES `knowledge` (`knowledge_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_knowledge_comments_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`users_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `knowledge_saves`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `knowledge_saves` (
  `knowledge_saves_id` varchar(16) NOT NULL,
  `user_id` varchar(16) DEFAULT NULL,
  `knowledge_id` varchar(16) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`knowledge_saves_id`),
  UNIQUE KEY `unique_save` (`user_id`,`knowledge_id`),
  KEY `knowledge_id` (`knowledge_id`),
  CONSTRAINT `fk_knowledge_saves_knowledge_id` FOREIGN KEY (`knowledge_id`) REFERENCES `knowledge` (`knowledge_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_knowledge_saves_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`users_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = utf8mb4 */ ;
/*!50003 SET character_set_results = utf8mb4 */ ;
/*!50003 SET collation_connection  = utf8mb4_general_ci */ ;
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION' */ ;
DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`localhost`*/ /*!50003 TRIGGER `update_knowledge_save_count` AFTER INSERT ON `knowledge_saves` FOR EACH ROW BEGIN
    UPDATE knowledge SET save_count = save_count + 1 WHERE knowledge_id = NEW.knowledge_id;
END */;;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = utf8mb4 */ ;
/*!50003 SET character_set_results = utf8mb4 */ ;
/*!50003 SET collation_connection  = utf8mb4_general_ci */ ;
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION' */ ;
DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`localhost`*/ /*!50003 TRIGGER `decrease_knowledge_save_count` AFTER DELETE ON `knowledge_saves` FOR EACH ROW BEGIN
    UPDATE knowledge SET save_count = save_count - 1 WHERE knowledge_id = OLD.knowledge_id;
END */;;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;
DROP TABLE IF EXISTS `knowledge_views`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `knowledge_views` (
  `knowledge_views_id` varchar(16) NOT NULL,
  `knowledge_id` varchar(16) DEFAULT NULL,
  `user_id` varchar(16) DEFAULT NULL,
  `viewed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`knowledge_views_id`),
  UNIQUE KEY `uq_knowledge_views_user` (`knowledge_id`,`user_id`),
  KEY `idx_knowledge_views` (`knowledge_id`),
  CONSTRAINT `fk_knowledge_views_knowledge_id` FOREIGN KEY (`knowledge_id`) REFERENCES `knowledge` (`knowledge_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `knowledge_votes`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `knowledge_votes` (
  `knowledge_votes_id` varchar(16) NOT NULL,
  `knowledge_id` varchar(16) DEFAULT NULL,
  `user_id` varchar(16) DEFAULT NULL,
  `vote` enum('helpful','not_helpful') NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`knowledge_votes_id`),
  UNIQUE KEY `unique_vote` (`knowledge_id`,`user_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `fk_knowledge_votes_knowledge_id` FOREIGN KEY (`knowledge_id`) REFERENCES `knowledge` (`knowledge_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_knowledge_votes_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`users_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `notifications`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `notifications` (
  `notifications_id` varchar(16) NOT NULL,
  `user_id` varchar(16) DEFAULT NULL,
  `type` enum('vote','save','comment','mention','system') NOT NULL,
  `message` text NOT NULL,
  `link` varchar(255) NOT NULL DEFAULT '',
  `is_read` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `from_user_id` varchar(16) DEFAULT NULL,
  PRIMARY KEY (`notifications_id`),
  KEY `idx_notifications_user` (`user_id`,`is_read`,`created_at`),
  KEY `from_user_id` (`from_user_id`),
  CONSTRAINT `fk_notifications_from_user_id` FOREIGN KEY (`from_user_id`) REFERENCES `users` (`users_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_notifications_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`users_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `users` (
  `users_id` varchar(16) NOT NULL,
  `department_id` varchar(16) DEFAULT NULL,
  `full_name` varchar(120) NOT NULL,
  `email` varchar(150) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `role` enum('admin','employee') NOT NULL DEFAULT 'employee',
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `profile_picture` varchar(255) NOT NULL DEFAULT '',
  `bio` text NOT NULL,
  `last_seen` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`users_id`),
  UNIQUE KEY `email` (`email`),
  KEY `department_id` (`department_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION' */ ;
/*!50003 DROP FUNCTION IF EXISTS `next_notification_id` */;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = utf8 */ ;
/*!50003 SET character_set_results = utf8 */ ;
/*!50003 SET collation_connection  = utf8_general_ci */ ;
DELIMITER ;;
CREATE DEFINER=`root`@`localhost` FUNCTION `next_notification_id`() RETURNS varchar(16) CHARSET utf8mb4 COLLATE utf8mb4_general_ci
    READS SQL DATA
BEGIN
    DECLARE v_next   INT DEFAULT 1;
    DECLARE v_id    VARCHAR(16) DEFAULT 'N001';
    DECLARE v_taken INT DEFAULT 0;
    DECLARE v_try   INT DEFAULT 0;

    SET v_next = COALESCE((
        SELECT MAX(CAST(SUBSTRING(notifications_id, 2) AS UNSIGNED))
        FROM notifications
        WHERE notifications_id REGEXP '^N[0-9]+$'
    ), 0) + 1;

    WHILE v_try < 5 DO
        SET v_id = CONCAT('N', LPAD(v_next, 3, '0'));
        SELECT COUNT(*) INTO v_taken FROM notifications WHERE notifications_id = v_id;
        IF v_taken = 0 THEN
            RETURN v_id;
        END IF;
        SET v_next = v_next + 1;
        SET v_try  = v_try + 1;
    END WHILE;

    RETURN v_id;
END ;;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;
/*!50001 DROP VIEW IF EXISTS `contribution_summary`*/;
/*!50001 SET @saved_cs_client          = @@character_set_client */;
/*!50001 SET @saved_cs_results         = @@character_set_results */;
/*!50001 SET @saved_col_connection     = @@collation_connection */;
/*!50001 SET character_set_client      = utf8mb4 */;
/*!50001 SET character_set_results     = utf8mb4 */;
/*!50001 SET collation_connection      = utf8mb4_general_ci */;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`root`@`localhost` SQL SECURITY DEFINER */
/*!50001 VIEW `contribution_summary` AS select `u`.`users_id` AS `users_id`,`u`.`full_name` AS `employee_name`,count(distinct `k`.`knowledge_id`) AS `total_articles`,count(`v`.`knowledge_votes_id`) AS `total_votes_received`,round(avg(case when `v`.`vote` = 'helpful' then 1.0 else 0.0 end),4) AS `helpful_ratio` from ((`users` `u` left join `knowledge` `k` on(`u`.`users_id` = `k`.`created_by`)) left join `knowledge_votes` `v` on(`k`.`knowledge_id` = `v`.`knowledge_id`)) group by `u`.`users_id`,`u`.`full_name` order by count(distinct `k`.`knowledge_id`) desc,`u`.`users_id` */;
/*!50001 SET character_set_client      = @saved_cs_client */;
/*!50001 SET character_set_results     = @saved_cs_results */;
/*!50001 SET collation_connection      = @saved_col_connection */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;


-- =====================================================================
-- REFERENCE DATA
-- Lookup values the application needs in order to function. No personal
-- information; they must be present on a fresh install.
-- =====================================================================

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `departments` WRITE;
/*!40000 ALTER TABLE `departments` DISABLE KEYS */;
INSERT INTO `departments` VALUES ('D001','IT Support','2026-09-01 19:21:21'),('D002','Network Administration','2026-09-01 19:21:21'),('D003','Systems Administration','2026-09-01 19:21:21'),('D004','Hardware Support','2026-09-01 19:21:21'),('D005','IT Security','2026-09-01 19:21:21');
/*!40000 ALTER TABLE `departments` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `knowledge_categories` WRITE;
/*!40000 ALTER TABLE `knowledge_categories` DISABLE KEYS */;
INSERT INTO `knowledge_categories` VALUES ('C001','Hardware','2026-09-02 03:21:21'),('C002','Network','2026-09-02 03:21:21'),('C003','Wi-Fi','2026-09-02 03:21:21'),('C004','Software','2026-09-02 03:21:21'),('C005','Server','2026-09-02 03:21:21'),('C006','Equipment','2026-09-02 03:21:21'),('C007','Security','2026-09-02 09:16:15'),('C008','Cloud','2026-09-02 09:16:15'),('C009','Database','2026-09-02 09:16:15');
/*!40000 ALTER TABLE `knowledge_categories` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

